services:
  - type: web
    name: teen-digital-literacy
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
  - type: worker
    name: ping-worker
    env: node
    buildCommand: npm install
    startCommand: npm run ping
    envVars:
      - key: NODE_ENV
        value: production

